### ISSUE TITLE
inbox-api and inbox-start suddenly broke

### ISSUE THREAD

**Issue by mandarvaze** [nylas/sync-engine#284] opened 2016-03-10 15:27 UTC
I have been using **local** setup for 12-13 days without any issues.
This afternoon, I suddenly saw following errors on both inbox-api as well as inbox-start

In `inbox-api` window :

```
vagrant@vagrant-ubuntu-precise-64:~$ cd /vagrant; bin/inbox-api
[INFO]  * Restarting with stat
[INFO] {"key": 3, "level": "info", "timestamp": "2016-03-10T15:18:09.321504Z", "hostname": "127.0.0.1", "module": "inbox.ignition:124", "schema_name": "inbox_3", "greenlet_id": 29381968, "event": "Not creating engine for disabled shard"}
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "bin/inbox-api", line 52, in <lambda>
    run_with_reloader(lambda: start(port, start_syncback))
  File "bin/inbox-api", line 63, in start
    from inbox.transactions.actions import SyncbackService
  File "/vagrant/inbox/transactions/actions.py", line 24, in <module>
    from inbox.actions.base import (mark_unread, mark_starred, move, change_labels,
  File "/vagrant/inbox/actions/base.py", line 26, in <module>
    from inbox.actions.backends.generic import (set_remote_unread,
  File "/vagrant/inbox/actions/backends/__init__.py", line 14, in <module>
    module_registry = register_backends(__name__, __path__)
  File "/vagrant/inbox/util/misc.py", line 173, in register_backends
    modules = load_modules(base_name, base_path)
  File "/vagrant/inbox/util/misc.py", line 159, in load_modules
    full_module_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/vagrant/inbox/actions/backends/generic.py", line 8, in <module>
    from inbox.mailsync.backends.imap.generic import uidvalidity_cb
  File "/vagrant/inbox/mailsync/backends/__init__.py", line 25, in <module>
    module_registry = register_backends(__name__, __path__)
  File "/vagrant/inbox/util/misc.py", line 173, in register_backends
    modules = load_modules(base_name, base_path)
  File "/vagrant/inbox/util/misc.py", line 159, in load_modules
    full_module_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/vagrant/inbox/mailsync/backends/gmail.py", line 36, in <module>
    from inbox.mailsync.backends.imap.generic import FolderSyncEngine
  File "/vagrant/inbox/mailsync/backends/imap/__init__.py", line 25, in <module>
    module_registry = register_backends(__name__, __path__)
  File "/vagrant/inbox/util/misc.py", line 173, in register_backends
    modules = load_modules(base_name, base_path)
  File "/vagrant/inbox/util/misc.py", line 158, in load_modules
    module = importer.find_module(module_name).load_module(
  File "/usr/lib/python2.7/pkgutil.py", line 186, in find_module
    file, filename, etc = imp.find_module(subname, path)
IOError: [Errno 21] Is a directory: '/vagrant/inbox/mailsync/backends/imap/generic.py'
```

On `inbox-start` window :

```
vagrant@vagrant-ubuntu-precise-64:~$ cd /vagrant/; bin/inbox-start
Traceback (most recent call last):
  File "bin/inbox-start", line 29, in <module>
    from inbox.mailsync.service import SyncService
  File "/vagrant/inbox/mailsync/service.py", line 20, in <module>
    from inbox.mailsync.backends import module_registry
  File "/vagrant/inbox/mailsync/backends/__init__.py", line 25, in <module>
    module_registry = register_backends(__name__, __path__)
  File "/vagrant/inbox/util/misc.py", line 173, in register_backends
    modules = load_modules(base_name, base_path)
  File "/vagrant/inbox/util/misc.py", line 159, in load_modules
    full_module_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/vagrant/inbox/mailsync/backends/gmail.py", line 36, in <module>
    from inbox.mailsync.backends.imap.generic import FolderSyncEngine
  File "/vagrant/inbox/mailsync/backends/imap/__init__.py", line 25, in <module>
    module_registry = register_backends(__name__, __path__)
  File "/vagrant/inbox/util/misc.py", line 173, in register_backends
    modules = load_modules(base_name, base_path)
  File "/vagrant/inbox/util/misc.py", line 158, in load_modules
    module = importer.find_module(module_name).load_module(
  File "/usr/lib/python2.7/pkgutil.py", line 186, in find_module
    file, filename, etc = imp.find_module(subname, path)
IOError: [Errno 21] Is a directory: '/vagrant/inbox/mailsync/backends/imap/generic.py'
vagrant@vagrant-ubuntu-precise-64:/vagrant$
```

I hardly look at these two sessions running in a separate window. So I have not made any changes to my vagrant images.

**are vagrant images self-updating ?**

**Comment by etagwerker** [comment] 2016-06-14 13:53
I can confirm that this is happening in my environment too for `inbox-api`

```
vagrant@vagrant-ubuntu-precise-64:/vagrant$ bin/inbox-api
[INFO]  * Restarting with stat
[INFO] {"key": 3, "level": "info", "timestamp": "2016-06-14T13:51:31.695758Z", "hostname": "127.0.0.1", "module": "inbox.ignition:124", "schema_name": "inbox_3", "greenlet_id": 56088368, "event": "Not creating engine for disabled shard"}
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "bin/inbox-api", line 52, in <lambda>
    run_with_reloader(lambda: start(port, start_syncback))
  File "bin/inbox-api", line 64, in start
    syncback = SyncbackService(0, 1)
TypeError: __init__() takes at least 4 arguments (3 given)
```

I didn't do anything weird, I just followed the instructions in the README. 

I'm using `master` at acce12f381778e3e31c30d8b627cfadb6313ea9e

The good news on my side is that `inbox-start` is working fine.

**Comment by acheloos-m** [comment] 2016-06-15 11:53
Yep, can also confirm this on Ubuntu 14.04 x64, fresh / local install with setup.sh.
`inbox-start` works as expected an syncs, only api will crash with same error message as @etagwerker posted.

**Comment by davidgross** [comment] 2016-06-15 15:33
I can also confirm this, on the vagrant machine that the Vagrantfile defines.

```
vagrant@vagrant-ubuntu-precise-64:~$ /vagrant/bin/inbox-api
[INFO]  * Restarting with stat
[INFO] {"key": 3, "level": "info", "timestamp": "2016-06-15T15:31:15.810969Z", "hostname": "127.0.0.1", "module": "inbox.ignition:124", "schema_name": "inbox_3", "greenlet_id": 44402480, "event": "Not creating engine for disabled shard"}
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/vagrant/bin/inbox-api", line 52, in <lambda>
    run_with_reloader(lambda: start(port, start_syncback))
  File "/vagrant/bin/inbox-api", line 64, in start
    syncback = SyncbackService(0, 1)
TypeError: __init__() takes at least 4 arguments (3 given)
```


```
vagrant@vagrant-ubuntu-precise-64:/vagrant$ bin/inbox-api 
[INFO]  * Restarting with stat
[INFO] {"key": 3, "level": "info", "timestamp": "2016-06-15T15:32:49.868975Z", "hostname": "127.0.0.1", "module": "inbox.ignition:124", "schema_name": "inbox_3", "greenlet_id": 34203440, "event": "Not creating engine for disabled shard"}
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "bin/inbox-api", line 52, in <lambda>
    run_with_reloader(lambda: start(port, start_syncback))
  File "bin/inbox-api", line 64, in start
    syncback = SyncbackService(0, 1)
TypeError: __init__() takes at least 4 arguments (3 given)

```

**Comment by EthanBlackburn** [comment] 2016-06-15 18:00
Hey folks, looks like this was because of a change we made recently to the syncback service. I've just push a fix to master(https://github.com/nylas/sync-engine/commit/774e397e17f3497079e823088900affc857567b6). Please pull in the latest changes and let me know if you continue to have problems running the sync service locally.

**Comment by siwymilek** [comment] 2016-08-16 12:30
there is still a problem for me

**Comment by grinich** [comment] 2017-01-31 01:29
Should be fixed now!

**Closed by grinich** 2017-01-31 01:29 UTC
