### ISSUE TITLE
exchange support

### ISSUE THREAD

**Issue by sakoula** [nylas/sync-engine#259] opened 2016-02-09 08:48 UTC
Hi,

I work for a company that hosts email in an exchange server (secured behind firewalls etc) exposing only Exchange protocols for the capable clients , SMTP (for sending mail) and POP3 (no IMAP). 

I would really love!!!!! to try nylas but cannot due to the fact that the opensource engine does not provide POP3 or exchange. Is there a slight chance that either of these protocols to be included in the open source sync-engine version?

Thanks!!!!!

**Comment by bherila** [comment] 2016-02-15 19:45
+1, why is Exchange not available in this source tree?

**Comment by jeremyFreeAgent** [comment] 2016-02-18 10:00
duplicate of #253

**Comment by khamidou** [comment] 2016-02-18 13:56
Unfortunately, we don't have plans to open source Exhange syncing at the moment.

**Closed by khamidou** 2016-02-18 13:56 UTC

**Comment by LeeSaferite** [comment] 2016-02-26 18:58
I know you have no obligation, but is there any chance you could explain the reasoning behind the decision to exclude the exchange portion?
