### ISSUE TITLE
bin/inbox-start and bin/inbox-api within one shell

### ISSUE THREAD

**Issue by screendriver** [nylas/sync-engine#237] opened 2015-12-02 06:25 UTC
Hi,

I am following the guide [Running Against Open Source Sync Engine](https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine) and [Installation and Setup](https://github.com/nylas/sync-engine#installation-and-setup). Everything works so far but could it be that I must do a

```sh
$ vagrant ssh
$ cd /vagrant
$ bin/inbox-start
````

in **one** shell window and following

```sh
$ vagrant ssh
$ cd /vagrant
$ bin/inbox-api
```

in a **second** shell window? Both commands seem to be running synchronous respectively blocking the shell?

**Comment by inboxskipper** [comment] 2015-12-02 08:43
Yep, that's right.





On Tue, Dec 1, 2015 at 10:26 PM -0800, "screendriver" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I am following the guide Running Against Open Source Sync Engine<https://github.com/nylas/N1/blob/master/CONTRIBUTING.md#running-against-open-source-sync-engine> and Installation and Setup<https://github.com/nylas/sync-engine#installation-and-setup>. Everything works so far but could it be that I must do a

$ vagrant ssh
$ cd /vagrant
$ bin/inbox-start

in one shell window and following

$ vagrant ssh
$ cd /vagrant
$ bin/inbox-api

in a second shell window? Both commands seem to be running synchronous respectively blocking the shell?

-

**Comment by screendriver** [comment] 2015-12-02 09:05
Ok. That should be mentioned in the docs :wink:

**Comment by camael24** [comment] 2016-01-16 11:16
i run `bin/inbox-start > /dev/null &` ctrl+x  and `bin/inbox-api > /dev/null &' but its maybe not the right way

**Comment by grinich** [comment] 2016-02-07 04:08
Going to close this because it's the intended behavior in order to keep the logs to STDOUT separate.

**Closed by grinich** 2016-02-07 04:08 UTC
