### ISSUE TITLE
libssl-dev required for Ubuntu Server 14.04

### ISSUE THREAD

**Issue by Proplex** [nylas/sync-engine#261] opened 2016-02-10 06:19 UTC
Heya,
I just recently deployed the sync-engine for my own use on a new Ubuntu Server, 14.04 box and halfway through the pip install for cryptography library, it fails with 

`fatal error: openssl/aes.h: No such file or directory
     #include <openssl/aes.h>`

This is fixed by installing libssl-dev. I have not tested this on any other OS, or setup, so I'm not sure if this should be added to setup.sh, but I'd argue to err on the side of safety and add it to the list of packages installed via apt in the beginning.

**Comment by tbelliard** [comment] 2016-02-17 12:12
Same issue is present with a fresh Debian 8 (Jessie) setup. Installing libssl-dev via apt also resolved the problem.

**Comment by singhkay** [comment] 2016-04-25 00:18
@Proplex Fixed in #295

**Comment by grinich** [comment] 2017-01-31 01:31
Closing due to stale and can't reproduce.

**Closed by grinich** 2017-01-31 01:31 UTC
