### ISSUE TITLE
Can't auth imap/smtp when email is different from username

### ISSUE THREAD

**Issue by claudioeddy** [nylas/sync-engine#230] opened 2015-11-24 15:56 UTC
I have the following settings working under Evolution email client (replaced my real and company name with 'first', 'last' and 'company' strings for practical issues):
```
IMAP settings
server: mbox.company.org.br
port: 143
username: first.last=company.org.br
encryption mode: STARTTLS after connecting

SMTP settings
server: smtp.company.org.br
port:587
encryption mode: none
authentication type: login with username first.last=company.org.br
```
But when I try to inbox-auth them, I get the following:
```
vagrant@precise64:/vagrant$ bin/inbox-auth first.last@company.org.br
IMAP account? [Y/n] y
Password for first.last@company.org.br (hidden): 
IMAP server host: mbox.company.org.br
IMAP server port: 143
SMTP server host: smtp.company.org.br
SMTP server port: 587
[ERROR] {"event": "IMAP login failed", "host": "mbox.company.org.br", "level": "error", "account_id": null, "error": "error('[AUTHENTICATIONFAILED] Authentication failed.',)", "timestamp": "2015-11-24T15:28:42.385707Z", "greenlet_id": 139877881151152, "email": "first.last@company.org.br", "module": "inbox.auth.generic:88", "port": 143}
Traceback (most recent call last):
  File "bin/inbox-auth", line 62, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 659, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "bin/inbox-auth", line 53, in main
    if auth_handler.verify_account(account):
  File "/vagrant/inbox/auth/generic.py", line 146, in verify_account
    conn = self.connect_account(account)
  File "/vagrant/inbox/auth/generic.py", line 89, in connect_account
    raise ValidationError(exc)
inbox.basicauth.ValidationError: [AUTHENTICATIONFAILED] Authentication failed.
```
It turns out I can't set an username different than my email when using inbox-auth.
https://github.com/nylas/sync-engine/pull/128 seems to be the solution to my problem, but I haven't figured out how to use such solution.
How should I proceed to make it work?
Thanks in advance.

**Comment by lkraav** [comment] 2015-12-02 01:40
Indeed, same here.

**Comment by wonzbak** [comment] 2016-01-13 14:39
Me too :(

**Comment by rbu** [comment] 2016-01-29 13:30
This is a duplicate of #110, is it not?

**Comment by grinich** [comment] 2016-02-07 03:57
this is fixed in https://github.com/nylas/sync-engine/commit/269709d7e3737f439c2cbec7b46dd8669fd60b54 !

**Closed by grinich** 2016-02-07 03:57 UTC

**Comment by lode** [comment] 2016-02-07 12:29
When does this fix go live? I still don't get such accounts set up.

**Comment by grinich** [comment] 2016-02-07 22:08
It requires a migration. We're hoping to have it done by Monday afternoon.
